apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: plugin-webhook
  namespace: demo
  labels:
    app: plugin-webhook
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: plugin-webhook
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - name: webhook
        image: aerokite/webhook-plugin
        imagePullPolicy: Always
        args:
        - run
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: plugin-webhook
  namespace: demo
  labels:
    app: plugin-webhook
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: plugin-webhook
  type: NodePort
