apiVersion: apps/v1
kind: Deployment
metadata:
  name: searchlight-plugin
  labels:
    app: searchlight-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searchlight-plugin
  template:
    metadata:
      labels:
        app: searchlight-plugin
    spec:
      serviceAccountName: searchlight-plugin
      containers:
      - name: webhook
        image: appscode/searchlight-plugin-go
        imagePullPolicy: Always
        args:
        - run
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: searchlight-plugin
  labels:
    app: searchlight-plugin
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: searchlight-plugin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: searchlight-plugin
  name: searchlight-plugin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: searchlight-plugin
  labels:
    app: searchlight-plugin
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: searchlight-plugin
  labels:
    app: searchlight-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: searchlight-plugin
subjects:
- kind: ServiceAccount
  name: searchlight-plugin
  namespace: default
---
